version: '3'
services:
  haulhelper-prod:
    image: prismagraphql/prisma:1.27
    restart: always
    ports:
    - "4222:4222"
    environment:
      PRISMA_CONFIG: |
        port: 4222
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          haulhelper-prod:
            database: haulhelper-prod
            connector: postgres
            host: postgres
            user: prisma
            password: prisma
            rawAccess: true
            port: 5432
            migrations: true
  haulhelper-dev:
    image: prismagraphql/prisma:1.27
    restart: always
    ports:
    - "4333:4333"
    environment:
      PRISMA_CONFIG: |
        port: 4333
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          haulhelper-prod:
            database: haulhelper-dev
            connector: postgres
            host: postgres
            user: prisma
            password: prisma
            rawAccess: true
            port: 5432
            migrations: true
  postgres:
    ports:
      - "3001:5432"
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
