version: '3'
services:
  haulhelper-prod:
    image: prismagraphql/prisma:1.29
    env_file:
    - .env
    restart: always
    ports:
    - "${PRISMA_PORT}:${PRISMA_PORT}"
    environment:
      PRISMA_CONFIG: |
        port: PRISMA_PORT
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          haulhelper-prod:
            database: haulhelper-prod
            connector: postgres
            host: postgres
            user: PRISMA_USERNAME
            password: PRISMA_PASSWORD
            rawAccess: true
            port: 5432
            migrations: true
  haulhelper-dev:
    image: prismagraphql/prisma:1.29
    env_file:
    - .env.dev
    restart: always
    ports:
    - "${PRISMA_PORT}:${PRISMA_PORT}"
    environment:
      PRISMA_CONFIG: |
        port: PRISMA_PORT
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          haulhelper-prod:
            database: haulhelper-dev
            connector: postgres
            host: postgres
            user: PRISMA_USERNAME
            password: PRISMA_PASSWORD
            rawAccess: true
            port: 5432
            migrations: true
  postgres:
    ports:
      - "3001:5432"
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: PRISMA_USERNAME
      POSTGRES_PASSWORD: PRISMA_PASSWORD
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
